Added booking component
JanvanZetten/BazarFrontEnd pull request #16
Opened 2018-12-03 13:43 UTC by Applemelon

2018-12-03 20:58 UTC, asbamse submitted a review, later dismissed
This should work

2018-12-04 08:38 UTC, JanvanZetten requested changes

2018-12-04 08:38 UTC, JanvanZetten commented on src/app/booking/booking.component.ts
> +    this.boothService.getUsersBooking();
Dette bliver aldrig sat ind der bør være en subscribe her med error håndtering

2018-12-04 08:39 UTC, asbamse commented on src/app/booking/booking.component.ts
> +    this.boothService.getUsersBooking();
Catch Error

2018-12-04 08:39 UTC, asbamse commented on src/app/booking/booking.component.html
> +  <h3>{{booth.id}}</h3>
Should write error if error occur.

2018-12-04 09:40 UTC, JanvanZetten requested changes

2018-12-04 09:40 UTC, JanvanZetten commented on src/app/shared/services/booth.service.ts
>      return this.http.post<Booth>(this.Url + '/', "\"" + this.authenticationService.getToken() + "\"", httpOptions);
Denne skal ikke sende til Post på booker med URL api/booths/ men til en specifik sti fx api/booths/usersBooking

2018-12-04 09:48 UTC, asbamse approved these changes
Good work guys

2018-12-04 09:48 UTC, JanvanZetten approved these changes

2018-12-04 09:48 UTC, merged